// This file is generated by the dismantle crate.
// It contains the masked payload, the XOR key, and the init_map function.
pub const MASKED_PAYLOAD: &[u8] = &[];
pub const XOR_KEY: &[u8] = &[];
pub fn init_map() -> std::collections::HashMap<usize, Vec<u8>> {
    std::collections::HashMap::new()
}
