[package]
name = "dismantle"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
iced-x86.workspace = true
clap.workspace = true
indexmap.workspace = true

[dependencies.windows]
version = "0.58"
features = [
    "Win32_Foundation",
    "Win32_System_Threading",
    "Win32_System_Memory",
    "Win32_System_Diagnostics_Debug",
    "Win32_System_Diagnostics_ToolHelp",
    "Win32_Security_Cryptography",
    "Win32_Storage_FileSystem",
    "Win32_UI_WindowsAndMessaging",
]

[[bin]]
name = "dismantle"
path = "src/main.rs"
